### ISSUE TITLE
Provide a standard algorithms/architectures libraries

### ISSUE THREAD

**Issue by ClementGGuy** [preesm/preesm-apps#1]
It would be useful to have a library of classical and reusable algorithms and architectures used in PREESM projects (split, merge, read...).
This could be a project containing a set of .pi, .graphml, .slam files provided by the PREESM team and managed as read only project for users.

**Comment by kdesnos** [comment]
Could probably be based on symlinks ?

**Comment by antoine-morvan** [comment]
This should be added directly in Preesm with wizard and/or context menu.
